[platformio]
default_envs = esp32-cyd
src_dir = sketches/esp32_cyd_starter
lib_dir = libraries

[env:esp32-cyd]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DCORE_DEBUG_LEVEL=1
